### ISSUE TITLE
s2s lookup error

### ISSUE THREAD

**Issue by waveletlet** [ortuman/jackal#77]
jackal can't find a server, even though `dig` shows it resolves correctly.

```
2019-03-11 23:51:42 💥 [ERR] s2s/server:94 - lookup _xmpp-server._tcp.riotcat.org on 9.9.9.9:53: no such host
```

```
# dig riotcat.org

; <<>> DiG 9.10.3-P4-Debian <<>> riotcat.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59702
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;riotcat.org.			IN	A

;; ANSWER SECTION:
riotcat.org.		3586	IN	A	87.106.127.220

;; Query time: 0 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Mon Mar 11 23:52:57 UTC 2019
;; MSG SIZE  rcvd: 56
```

The error is consistent, I can't get any kind of connection to that server at all.

This isn't a global issue, I can successfully connect to other servers and send messages to users on them. According to [compliance.conversations.im](https://compliance.conversations.im/server/riotcat.org/), the remote server is running Prosody 0.11. 

Then when I was checking logs for more errors, I found that a server I can successfully communicate on is also returning the same error occasionally (`2019-03-12 01:54:52 💥 [ERR] s2s/server:94 - lookup _xmpp-server._tcp.chat.404.city on 9.9.9.9:53: no such host`). The remote server with the intermittent error is running  ejabberd 18.12.1-2~bpo9+1.

Maybe it's something I can tweak in the config? s2s section of jackal.yml is the same as in the example:

```
s2s:
    dial_timeout: 15
    dialback_secret: s3cr3tf0rd14lb4ck
    max_stanza_size: 131072

    transport:
      bind_addr: 0.0.0.0
      port: 5269
      keep_alive: 600
```

**Comment by waveletlet** [comment]
Also, it looks like I can receive messages from the server that lookup always fails for.

**Comment by waveletlet** [comment]
Better dig lookup:

```
dig SRV _xmpp-client._tcp.riotcat.org

; <<>> DiG 9.11.5-P4-1-Debian <<>> SRV _xmpp-client._tcp.riotcat.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20350
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_xmpp-client._tcp.riotcat.org.	IN	SRV

;; AUTHORITY SECTION:
riotcat.org.		300	IN	SOA	ns1042.ui-dns.org. hostmaster.kundenserver.de. 2016020102 28800 7200 604800 300

;; Query time: 261 msec
;; SERVER: 85.214.20.141#53(85.214.20.141)
;; WHEN: Tue Mar 12 23:08:09 -03 2019
;; MSG SIZE  rcvd: 134
```

**Comment by waveletlet** [comment]
Ok, I did some more debugging, it looks like the error is when it runs `net.LookupSRV("xmpp-server", "tcp", "riotcat.org")`. Possibly an occurance of [this bug](https://github.com/golang/go/issues/18588).

Other failed debugging to try to get around this bug, as hinted at by comments in the bug linked above:
* setting limit of open files to unlimited (/etc/security/limits.conf)
* changing to possibly faster dns servers (to decrease chance of timeout, tried google's 8.8.8.8 and cloudflare's 1.1.1.1)

It's probably a combination of how the server in question set up its DNS, and how go handles DNS lookups. Not sure if there's a way around this. Besides maybe a hack to try using the system's 'dig' command (if present) if the lookup by net.LookupSRV fails.

**Comment by ortuman** [comment]
Yes, you are right. Right now, if the service fails trying to do the SRV lookup we do not fallback to the standard XMPP port...
https://github.com/ortuman/jackal/blob/master/s2s/dial.go#L31-L40

Thanks for reporting. I'll update the issue as soon as the patch is applied.

**Comment by ortuman** [comment]
This commit should fix the issue...

https://github.com/ortuman/jackal/commit/e7bb957e67ba0664d3517d30f1a48b8cf3dec4f1

Available on master branch, please @waveletlet could you confirm it's working now? Thanks! 🙏

**Comment by waveletlet** [comment]
I also talked to the person running the server, and they told me they only set xmpps-client/xmpps-server, to force secure connections as described in [XEP-0368](https://xmpp.org/extensions/xep-0368.html), might be good to also try something like `d.srvResolve("xmpps-server", "tcp", remoteDomain)` for that case (which is probably the preferred case, anyway).

**Comment by waveletlet** [comment]
Looks like it works now! But I'm not seeing this warning `log.Warnf("srv lookup error: %v", err)` in the log, should I be? The remote server admin said they'd add the SRV record so I'm not sure if it'd trigger the error or not anymore. (`dig` still isn't giving me a SRV record for them, though.)
